language: node_js
node_js:
  - '0.10'
  - '0.8'
  - '0.6'

before_script:
  - cp test/config.js.dist test/config.js
  - mysql -e 'create database node_dbi_test;'
  - psql -c 'create database node_dbi_test;' -U postgres
